services:
  otcclaw:
    environment:
      PG_WIND_HOST: wind_sync_pg
      PG_WIND_PORT: 5432
      FAST_TRADING_PG_HOST: wind_sync_pg
      FAST_TRADING_PG_PORT: 5432
      WIND_PG_HOST: wind_sync_pg
      WIND_PG_PORT: 5432
      LOG_PG_HOST: wind_sync_pg
      LOG_PG_PORT: 5432
    networks:
      - wind-sync

networks:
  wind-sync:
    external: true
    name: samata-wind-sync
