*

!samata/
!samata/**
!samata-plugins/
!samata-plugins/**

samata/.git
samata/.git/**
samata/node_modules
samata/node_modules/**
samata/data
samata/data/**
samata/logs
samata/logs/**
samata/.env*
!samata/.env.example
!samata/.env.langfuse.example

samata-plugins/.git
samata-plugins/.git/**
samata-plugins/node_modules
samata-plugins/node_modules/**
samata-plugins/**/node_modules
samata-plugins/**/node_modules/**
samata-plugins/.env*
