type MutableEnvironment = Record<string, string | undefined>;

const SFTP_COMPATIBILITY_ALIASES: ReadonlyArray<readonly [target: string, source: string]> = [
  ['SFTP_PASSWD', 'SFTP_PASSWORD'],
  ['SFTP_REMOTE_BASE', 'SFTP_FAST_TRADES_REMOTE_BASE'],
  ['NORMAL_TRADING_SFTP_HOST', 'SFTP_HOST'],
  ['NORMAL_TRADING_SFTP_PORT', 'SFTP_PORT'],
  ['NORMAL_TRADING_SFTP_USER', 'SFTP_USER'],
  ['NORMAL_TRADING_SFTP_PASSWORD', 'SFTP_PASSWORD'],
  ['NORMAL_TRADING_SFTP_PASSWD', 'SFTP_PASSWORD'],
  ['NORMAL_TRADING_SFTP_TRADES_REMOTE_BASE', 'SFTP_NORMAL_TRADES_REMOTE_BASE'],
  ['NORMAL_TRADING_SFTP_BUSINESS_SCALE_REMOTE_BASE', 'SFTP_NORMAL_SUMMARY_REMOTE_BASE'],
  ['NORMAL_TRADING_SFTP_POSITION_DETAILS_REMOTE_BASE', 'SFTP_NORMAL_POSITION_DETAILS_REMOTE_BASE'],
  ['NORMAL_TRADING_SFTP_REMOTE_BASE', 'SFTP_NORMAL_SUMMARY_REMOTE_BASE'],
  ['FAST_TRADING_SFTP_HOST', 'SFTP_HOST'],
  ['FAST_TRADING_SFTP_PORT', 'SFTP_PORT'],
  ['FAST_TRADING_SFTP_USER', 'SFTP_USER'],
  ['FAST_TRADING_SFTP_PASSWORD', 'SFTP_PASSWORD'],
  ['FAST_TRADING_SFTP_PASSWD', 'SFTP_PASSWORD'],
  ['FAST_TRADING_SFTP_REMOTE_BASE', 'SFTP_FAST_SUMMARY_REMOTE_BASE'],
  ['CORPACTIONSFTP_HOST', 'SFTP_HOST'],
  ['CORPACTIONSFTP_USER', 'SFTP_USER'],
  ['CORPACTIONSFTP_PASSWORD', 'SFTP_PASSWORD'],
  ['CORP_ACTION_SFTP_HOST', 'SFTP_HOST'],
  ['CORP_ACTION_SFTP_PORT', 'SFTP_PORT'],
  ['CORP_ACTION_SFTP_USER', 'SFTP_USER'],
  ['CORP_ACTION_SFTP_PASSWORD', 'SFTP_PASSWORD'],
  ['CORP_ACTION_SFTP_PASSWD', 'SFTP_PASSWORD'],
  ['CORP_ACTION_SFTP_REMOTE_BASE', 'SFTP_CORPORATE_ACTION_REMOTE_BASE'],
  ['SBL_SFTP_HOST', 'SFTP_HOST'],
  ['SBL_SFTP_PORT', 'SFTP_PORT'],
  ['SBL_SFTP_USER', 'SFTP_USER'],
  ['SBL_SFTP_PASSWD', 'SFTP_PASSWORD'],
  ['SBL_SFTP_REMOTE_BASE', 'SFTP_SBL_REMOTE_BASE'],
  ['HEDGE_RATIO_SFTP_ENABLED', 'SFTP_HEDGE_ENABLED'],
  ['HEDGE_RATIO_SFTP_HOST', 'SFTP_HOST'],
  ['HEDGE_RATIO_SFTP_PORT', 'SFTP_PORT'],
  ['HEDGE_RATIO_SFTP_USERNAME', 'SFTP_USER'],
  ['HEDGE_RATIO_SFTP_PASSWORD', 'SFTP_PASSWORD'],
  ['HEDGE_RATIO_SFTP_REMOTE_BASE_PATH', 'SFTP_HEDGE_REMOTE_BASE'],
];

/**
 * Keep deployment configuration in one SFTP_* namespace while packaged
 * plugins transition away from their historical variable names.
 *
 * A configured unified value always wins over an ambient legacy value.
 */
export function applySftpCompatibilityAliases(
  environment: MutableEnvironment = process.env,
): void {
  for (const [target, source] of SFTP_COMPATIBILITY_ALIASES) {
    const value = environment[source];
    if (value !== undefined && value !== '') environment[target] = value;
  }
}
