// Generated by scripts/sync-docs-plan-index.ts. Do not edit manually.

export type DocModule = 'platform' | 'permissions' | 'dream' | 'plugins' | 'external-data';

export type PlanIndexItem = {
  title: string;
  link: string;
  sourcePath: string;
  sortKey: string;
  date: string | null;
  status: string;
  topic: string;
  canonicalDocs: string[];
};

export const planModuleLabels: Record<DocModule, string> = {
  "platform": "平台介绍",
  "permissions": "权限控制",
  "dream": "Dream",
  "plugins": "插件机制",
  "external-data": "外部数据"
};

export const planIndexByModule: Record<DocModule, PlanIndexItem[]> = {
  "platform": [
    {
      "title": "Agent Skills 管理机制",
      "link": "/plan/agent-skills-management",
      "sourcePath": "docs/plan/agent-skills-management.md",
      "sortKey": "agent-skills-management.md",
      "date": null,
      "status": "implemented",
      "canonicalDocs": [
        "/plugins/sdk-and-lifecycle",
        "/platform/agent-capability-model"
      ],
      "topic": "Agent 能力模型"
    },
    {
      "title": "定时任务设置权限与授权运行",
      "link": "/plan/2026-06-04_scheduled-task-admin-authorized-run",
      "sourcePath": "docs/plan/2026-06-04_scheduled-task-admin-authorized-run.md",
      "sortKey": "2026-06-04_scheduled-task-admin-authorized-run.md",
      "date": "2026-06-04",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/common-tools",
        "/permissions/tool-access"
      ],
      "topic": "调度与任务"
    },
    {
      "title": "Docker 镜像版本化 Tag 与清理",
      "link": "/plan/2026-06-04_docker-image-version-tags",
      "sourcePath": "docs/plan/2026-06-04_docker-image-version-tags.md",
      "sortKey": "2026-06-04_docker-image-version-tags.md",
      "date": "2026-06-04",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/deployment"
      ],
      "topic": "部署与运行"
    },
    {
      "title": "Samata 本地运行时改动推送 GitHub",
      "link": "/plan/2026-06-03_push-samata-runtime-updates-to-github",
      "sourcePath": "docs/plan/2026-06-03_push-samata-runtime-updates-to-github.md",
      "sortKey": "2026-06-03_push-samata-runtime-updates-to-github.md",
      "date": "2026-06-03",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/deployment"
      ],
      "topic": "部署与运行"
    },
    {
      "title": "旧 InfluxDB 监控与 north_info 迁移脚本清理",
      "link": "/plan/2026-06-03_legacy-influxdb-monitor-cleanup",
      "sourcePath": "docs/plan/2026-06-03_legacy-influxdb-monitor-cleanup.md",
      "sortKey": "2026-06-03_legacy-influxdb-monitor-cleanup.md",
      "date": "2026-06-03",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/architecture",
        "/external-data/pricing-and-trade"
      ],
      "topic": "插件生命周期与平台边界"
    },
    {
      "title": "Docker 部署运行时支持",
      "link": "/plan/2026-06-03_docker-deployment-runtime",
      "sourcePath": "docs/plan/2026-06-03_docker-deployment-runtime.md",
      "sortKey": "2026-06-03_docker-deployment-runtime.md",
      "date": "2026-06-03",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/deployment"
      ],
      "topic": "部署与运行"
    },
    {
      "title": "变更留档、提交与推送规范",
      "link": "/plan/2026-06-03_change-archive-commit-push-rule",
      "sourcePath": "docs/plan/2026-06-03_change-archive-commit-push-rule.md",
      "sortKey": "2026-06-03_change-archive-commit-push-rule.md",
      "date": "2026-06-03",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/architecture"
      ],
      "topic": "工程规范"
    },
    {
      "title": "Samata MVP 部署指南 — 以 Moss Agent 为例",
      "link": "/plan/2026-05-25_moss-deployment-guide",
      "sourcePath": "docs/plan/2026-05-25_moss-deployment-guide.md",
      "sortKey": "2026-05-25_moss-deployment-guide.md",
      "date": "2026-05-25",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/deployment"
      ],
      "topic": "部署与模型"
    },
    {
      "title": "Samata 双 Repo 拆分 + Agent 配置/数据管理方案",
      "link": "/plan/2026-05-24_samata-repo-split",
      "sourcePath": "docs/plan/2026-05-24_samata-repo-split.md",
      "sortKey": "2026-05-24_samata-repo-split.md",
      "date": "2026-05-24",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/deployment"
      ],
      "topic": "部署与模型"
    },
    {
      "title": "Samata 项目重构：核心平台 + 独立工具插件",
      "link": "/plan/2026-05-21_samata-refactor-plugin-based",
      "sourcePath": "docs/plan/2026-05-21_samata-refactor-plugin-based.md",
      "sortKey": "2026-05-21_samata-refactor-plugin-based.md",
      "date": "2026-05-21",
      "status": "implemented",
      "canonicalDocs": [
        "/plugins/sdk-and-lifecycle",
        "/platform/architecture"
      ],
      "topic": "平台边界"
    },
    {
      "title": "Web 调用无结论问题改进",
      "link": "/plan/2026-05-06_web-browsing-loop-fix",
      "sourcePath": "docs/plan/2026-05-06_web-browsing-loop-fix.md",
      "sortKey": "2026-05-06_web-browsing-loop-fix.md",
      "date": "2026-05-06",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/web-and-browser",
        "/platform/observability"
      ],
      "topic": "观测与稳定性"
    },
    {
      "title": "2026-04-29 异常会话根因分析",
      "link": "/plan/2026-04-30_loop-root-cause-analysis",
      "sourcePath": "docs/plan/2026-04-30_loop-root-cause-analysis.md",
      "sortKey": "2026-04-30_loop-root-cause-analysis.md",
      "date": "2026-04-30",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/observability",
        "/external-data/web-and-browser"
      ],
      "topic": "观测与稳定性"
    },
    {
      "title": "Agent Wiki 知识库改造计划",
      "link": "/plan/2026-04-28_agent-wiki-knowledge",
      "sourcePath": "docs/plan/2026-04-28_agent-wiki-knowledge.md",
      "sortKey": "2026-04-28_agent-wiki-knowledge.md",
      "date": "2026-04-28",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/wiki-and-doc-sources",
        "/platform/agent-capability-model"
      ],
      "topic": "文档与知识"
    },
    {
      "title": "关闭 Slide 4 \"观测与调优\" 宣传与实现的差距",
      "link": "/plan/2026-04-24_slide4-observability-gap",
      "sourcePath": "docs/plan/2026-04-24_slide4-observability-gap.md",
      "sortKey": "2026-04-24_slide4-observability-gap.md",
      "date": "2026-04-24",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/observability",
        "/dream/quality"
      ],
      "topic": "观测与稳定性"
    },
    {
      "title": "DeepSeek 官方 Provider",
      "link": "/plan/2026-04-24_deepseek-provider",
      "sourcePath": "docs/plan/2026-04-24_deepseek-provider.md",
      "sortKey": "2026-04-24_deepseek-provider.md",
      "date": "2026-04-24",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/deployment"
      ],
      "topic": "部署与模型"
    },
    {
      "title": "2026-04-24 Claude Code 接入广发 Anthropic 网关（本地拍平代理）",
      "link": "/plan/2026-04-24_claude-gf-anthropic-proxy",
      "sourcePath": "docs/plan/2026-04-24_claude-gf-anthropic-proxy.md",
      "sortKey": "2026-04-24_claude-gf-anthropic-proxy.md",
      "date": "2026-04-24",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/deployment"
      ],
      "topic": "部署与模型"
    },
    {
      "title": "Session 持久化与用户记忆注入（纯文件版）",
      "link": "/plan/2026-04-22_session-workspace-user-context",
      "sourcePath": "docs/plan/2026-04-22_session-workspace-user-context.md",
      "sortKey": "2026-04-22_session-workspace-user-context.md",
      "date": "2026-04-22",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/channels-and-sessions"
      ],
      "topic": "渠道与会话"
    },
    {
      "title": "日期时间感知增强计划",
      "link": "/plan/2026-04-21_datetime-awareness",
      "sourcePath": "docs/plan/2026-04-21_datetime-awareness.md",
      "sortKey": "2026-04-21_datetime-awareness.md",
      "date": "2026-04-21",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/common-tools"
      ],
      "topic": "通用工具"
    },
    {
      "title": "执行计划：文档知识从 DB 存储改为 Markdown 文件 + Grep 查询",
      "link": "/plan/2026-04-20_documents-markdown-grep",
      "sourcePath": "docs/plan/2026-04-20_documents-markdown-grep.md",
      "sortKey": "2026-04-20_documents-markdown-grep.md",
      "date": "2026-04-20",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/agent-capability-model",
        "/external-data/wiki-and-doc-sources"
      ],
      "topic": "文档与知识"
    },
    {
      "title": "评审：文档知识 DB → Markdown + Grep 方案",
      "link": "/plan/2026-04-20_documents-markdown-grep_review",
      "sourcePath": "docs/plan/2026-04-20_documents-markdown-grep_review.md",
      "sortKey": "2026-04-20_documents-markdown-grep_review.md",
      "date": "2026-04-20",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/agent-capability-model",
        "/external-data/wiki-and-doc-sources"
      ],
      "topic": "文档与知识"
    },
    {
      "title": "CLI：知识标签与 monitor 白名单核对",
      "link": "/plan/2026-04-14_knowledge-tags-cli-audit",
      "sourcePath": "docs/plan/2026-04-14_knowledge-tags-cli-audit.md",
      "sortKey": "2026-04-14_knowledge-tags-cli-audit.md",
      "date": "2026-04-14",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/agent-capability-model"
      ],
      "topic": "文档与知识"
    },
    {
      "title": "文档知识导入与管理",
      "link": "/plan/2026-04-14_document-knowledge-import",
      "sourcePath": "docs/plan/2026-04-14_document-knowledge-import.md",
      "sortKey": "2026-04-14_document-knowledge-import.md",
      "date": "2026-04-14",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/agent-capability-model"
      ],
      "topic": "文档与知识"
    },
    {
      "title": "文档文件持久化存储",
      "link": "/plan/2026-04-14_document-file-persistence",
      "sourcePath": "docs/plan/2026-04-14_document-file-persistence.md",
      "sortKey": "2026-04-14_document-file-persistence.md",
      "date": "2026-04-14",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/agent-capability-model"
      ],
      "topic": "文档与知识"
    },
    {
      "title": "Agent 成员 user blocklist：文档导入/删除",
      "link": "/plan/2026-04-14_agent-user-blocklist-document-tools",
      "sourcePath": "docs/plan/2026-04-14_agent-user-blocklist-document-tools.md",
      "sortKey": "2026-04-14_agent-user-blocklist-document-tools.md",
      "date": "2026-04-14",
      "status": "implemented",
      "canonicalDocs": [
        "/permissions/resource-scopes",
        "/platform/agent-capability-model"
      ],
      "topic": "文档与知识"
    },
    {
      "title": "OTC Claw（衍语）功能架构说明",
      "link": "/plan/2026-04-12_otcclaw-architecture-overview",
      "sourcePath": "docs/plan/2026-04-12_otcclaw-architecture-overview.md",
      "sortKey": "2026-04-12_otcclaw-architecture-overview.md",
      "date": "2026-04-12",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/agent-capability-model",
        "/external-data/pricing-and-trade",
        "/plugins/sdk-and-lifecycle"
      ],
      "topic": "Agent 能力模型"
    },
    {
      "title": "Remote CLI Interactive Prompts",
      "link": "/plan/2026-04-09_remote-cli-interactive-prompts",
      "sourcePath": "docs/plan/2026-04-09_remote-cli-interactive-prompts.md",
      "sortKey": "2026-04-09_remote-cli-interactive-prompts.md",
      "date": "2026-04-09",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/channels-and-sessions"
      ],
      "topic": "渠道与会话"
    },
    {
      "title": "企微智能机器人：长连接接入（详细实施方案）",
      "link": "/plan/2026-04-08_wework-aibot-long-connection",
      "sourcePath": "docs/plan/2026-04-08_wework-aibot-long-connection.md",
      "sortKey": "2026-04-08_wework-aibot-long-connection.md",
      "date": "2026-04-08",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/channels-and-sessions"
      ],
      "topic": "渠道与会话"
    },
    {
      "title": "Add Text-to-Image and Text-to-Video Generation",
      "link": "/plan/2026-04-06_media-generation",
      "sourcePath": "docs/plan/2026-04-06_media-generation.md",
      "sortKey": "2026-04-06_media-generation.md",
      "date": "2026-04-06",
      "status": "implemented",
      "canonicalDocs": [
        "/plugins/catalog",
        "/platform/common-tools"
      ],
      "topic": "通用工具"
    },
    {
      "title": "Agent 权限梳理与建议",
      "link": "/plan/2026-04-03_server-cli-channel-rbac",
      "sourcePath": "docs/plan/2026-04-03_server-cli-channel-rbac.md",
      "sortKey": "2026-04-03_server-cli-channel-rbac.md",
      "date": "2026-04-03",
      "status": "implemented",
      "canonicalDocs": [
        "/permissions/channel-isolation",
        "/platform/channels-and-sessions"
      ],
      "topic": "渠道与会话"
    },
    {
      "title": "Plan: Markdown → Image Tool",
      "link": "/plan/2026-03-30_markdown-to-image-tool",
      "sourcePath": "docs/plan/2026-03-30_markdown-to-image-tool.md",
      "sortKey": "2026-03-30_markdown-to-image-tool.md",
      "date": "2026-03-30",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/common-tools",
        "/plugins/catalog"
      ],
      "topic": "通用工具"
    },
    {
      "title": "Todo List Tracking Tools",
      "link": "/plan/2026-03-26_todo-tools",
      "sourcePath": "docs/plan/2026-03-26_todo-tools.md",
      "sortKey": "2026-03-26_todo-tools.md",
      "date": "2026-03-26",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/common-tools"
      ],
      "topic": "通用工具"
    },
    {
      "title": "执行计划: 飞书 Bot 动态启停支持",
      "link": "/plan/2026-03-21_feishu-bot-dynamic-control",
      "sourcePath": "docs/plan/2026-03-21_feishu-bot-dynamic-control.md",
      "sortKey": "2026-03-21_feishu-bot-dynamic-control.md",
      "date": "2026-03-21",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/channels-and-sessions"
      ],
      "topic": "渠道与会话"
    },
    {
      "title": "定时提醒任务 (Reminder) Common Tools 设计方案",
      "link": "/plan/2026-03-20_reminder-tools",
      "sourcePath": "docs/plan/2026-03-20_reminder-tools.md",
      "sortKey": "2026-03-20_reminder-tools.md",
      "date": "2026-03-20",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/common-tools"
      ],
      "topic": "通用工具"
    },
    {
      "title": "企微监测 Tools 化计划",
      "link": "/plan/2026-03-19_wework-monitor-tool",
      "sourcePath": "docs/plan/2026-03-19_wework-monitor-tool.md",
      "sortKey": "2026-03-19_wework-monitor-tool.md",
      "date": "2026-03-19",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/channels-and-sessions",
        "/plugins/catalog"
      ],
      "topic": "渠道与会话"
    },
    {
      "title": "Plan: Fix /status skill count inconsistency between Feishu and CLI",
      "link": "/plan/2026-03-19_feishu-status-agent-context",
      "sourcePath": "docs/plan/2026-03-19_feishu-status-agent-context.md",
      "sortKey": "2026-03-19_feishu-status-agent-context.md",
      "date": "2026-03-19",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/channels-and-sessions"
      ],
      "topic": "渠道与会话"
    },
    {
      "title": "feishu bot 凭证迁移到 DB + wework-monitor 使用 alter-ego 绑定",
      "link": "/plan/2026-03-19_feishu-bot-migrate-to-db",
      "sourcePath": "docs/plan/2026-03-19_feishu-bot-migrate-to-db.md",
      "sortKey": "2026-03-19_feishu-bot-migrate-to-db.md",
      "date": "2026-03-19",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/channels-and-sessions"
      ],
      "topic": "渠道与会话"
    }
  ],
  "permissions": [
    {
      "title": "Memory 权限隔离方案",
      "link": "/plan/memory_permission_scoping_5b2610bc.plan",
      "sourcePath": "docs/plan/memory_permission_scoping_5b2610bc.plan.md",
      "sortKey": "memory_permission_scoping_5b2610bc.plan.md",
      "date": null,
      "status": "implemented",
      "canonicalDocs": [
        "/permissions/resource-scopes"
      ],
      "topic": "资源作用域"
    },
    {
      "title": "定时任务设置权限与授权运行",
      "link": "/plan/2026-06-04_scheduled-task-admin-authorized-run",
      "sourcePath": "docs/plan/2026-06-04_scheduled-task-admin-authorized-run.md",
      "sortKey": "2026-06-04_scheduled-task-admin-authorized-run.md",
      "date": "2026-06-04",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/common-tools",
        "/permissions/tool-access"
      ],
      "topic": "Agent 权限"
    },
    {
      "title": "TiClaw 沙箱 + Wind 数据库能力（2026-05-08）",
      "link": "/plan/2026-05-08_ticlaw-sandbox-wind",
      "sourcePath": "docs/plan/2026-05-08_ticlaw-sandbox-wind.md",
      "sortKey": "2026-05-08_ticlaw-sandbox-wind.md",
      "date": "2026-05-08",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/wind-sandbox",
        "/permissions/file-and-sandbox-allowlist"
      ],
      "topic": "文件与沙箱白名单"
    },
    {
      "title": "Agent read_file 白名单",
      "link": "/plan/2026-04-27_agent-read-file-allowlist",
      "sourcePath": "docs/plan/2026-04-27_agent-read-file-allowlist.md",
      "sortKey": "2026-04-27_agent-read-file-allowlist.md",
      "date": "2026-04-27",
      "status": "implemented",
      "canonicalDocs": [
        "/permissions/file-and-sandbox-allowlist",
        "/external-data/wind-sandbox"
      ],
      "topic": "文件与沙箱白名单"
    },
    {
      "title": "Agent 成员 user blocklist：文档导入/删除",
      "link": "/plan/2026-04-14_agent-user-blocklist-document-tools",
      "sourcePath": "docs/plan/2026-04-14_agent-user-blocklist-document-tools.md",
      "sortKey": "2026-04-14_agent-user-blocklist-document-tools.md",
      "date": "2026-04-14",
      "status": "implemented",
      "canonicalDocs": [
        "/permissions/resource-scopes",
        "/platform/agent-capability-model"
      ],
      "topic": "资源作用域"
    },
    {
      "title": "Agent 工具权限矩阵重构",
      "link": "/plan/2026-04-07_agent-tools-matrix-refactor",
      "sourcePath": "docs/plan/2026-04-07_agent-tools-matrix-refactor.md",
      "sortKey": "2026-04-07_agent-tools-matrix-refactor.md",
      "date": "2026-04-07",
      "status": "implemented",
      "canonicalDocs": [
        "/permissions/tool-access",
        "/plugins/bind-to-agent"
      ],
      "topic": "工具可见性"
    },
    {
      "title": "飞书用户权限控制修复",
      "link": "/plan/2026-04-06_feishu-permission-control",
      "sourcePath": "docs/plan/2026-04-06_feishu-permission-control.md",
      "sortKey": "2026-04-06_feishu-permission-control.md",
      "date": "2026-04-06",
      "status": "implemented",
      "canonicalDocs": [
        "/permissions/channel-isolation"
      ],
      "topic": "渠道隔离"
    },
    {
      "title": "Agent 权限梳理与建议",
      "link": "/plan/2026-04-03_server-cli-channel-rbac",
      "sourcePath": "docs/plan/2026-04-03_server-cli-channel-rbac.md",
      "sortKey": "2026-04-03_server-cli-channel-rbac.md",
      "date": "2026-04-03",
      "status": "implemented",
      "canonicalDocs": [
        "/permissions/channel-isolation",
        "/platform/channels-and-sessions"
      ],
      "topic": "渠道隔离"
    },
    {
      "title": "Samata vs OpenClaw vs Claude Code: Skill & Tool 架构对比分析",
      "link": "/plan/2026-04-02_skill-tool-architecture-comparison",
      "sourcePath": "docs/plan/2026-04-02_skill-tool-architecture-comparison.md",
      "sortKey": "2026-04-02_skill-tool-architecture-comparison.md",
      "date": "2026-04-02",
      "status": "implemented",
      "canonicalDocs": [
        "/plugins/sdk-and-lifecycle",
        "/permissions/tool-access"
      ],
      "topic": "工具可见性"
    },
    {
      "title": "User Management CLI Execution Plan",
      "link": "/plan/2026-03-27_user-management",
      "sourcePath": "docs/plan/2026-03-27_user-management.md",
      "sortKey": "2026-03-27_user-management.md",
      "date": "2026-03-27",
      "status": "implemented",
      "canonicalDocs": [
        "/permissions/roles-and-rbac"
      ],
      "topic": "用户管理"
    },
    {
      "title": "执行计划：Agent 级别权限管理与系统管理员隔离",
      "link": "/plan/2026-03-16_agent-rbac-auth",
      "sourcePath": "docs/plan/2026-03-16_agent-rbac-auth.md",
      "sortKey": "2026-03-16_agent-rbac-auth.md",
      "date": "2026-03-16",
      "status": "implemented",
      "canonicalDocs": [
        "/permissions/roles-and-rbac"
      ],
      "topic": "RBAC 与 Agent 成员"
    }
  ],
  "dream": [
    {
      "title": "丰富 Dream 数据源 + 改善提取质量",
      "link": "/plan/2026-05-12_enrich-dream-quality",
      "sourcePath": "docs/plan/2026-05-12_enrich-dream-quality.md",
      "sortKey": "2026-05-12_enrich-dream-quality.md",
      "date": "2026-05-12",
      "status": "implemented",
      "canonicalDocs": [
        "/dream/quality"
      ],
      "topic": "质量与观测"
    },
    {
      "title": "关闭 Slide 4 \"观测与调优\" 宣传与实现的差距",
      "link": "/plan/2026-04-24_slide4-observability-gap",
      "sourcePath": "docs/plan/2026-04-24_slide4-observability-gap.md",
      "sortKey": "2026-04-24_slide4-observability-gap.md",
      "date": "2026-04-24",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/observability",
        "/dream/quality"
      ],
      "topic": "质量与观测"
    }
  ],
  "plugins": [
    {
      "title": "Agent Skills 管理机制",
      "link": "/plan/agent-skills-management",
      "sourcePath": "docs/plan/agent-skills-management.md",
      "sortKey": "agent-skills-management.md",
      "date": null,
      "status": "implemented",
      "canonicalDocs": [
        "/plugins/sdk-and-lifecycle",
        "/platform/agent-capability-model"
      ],
      "topic": "Skill 机制"
    },
    {
      "title": "Samata 本地运行时改动推送 GitHub",
      "link": "/plan/2026-06-03_push-samata-runtime-updates-to-github",
      "sourcePath": "docs/plan/2026-06-03_push-samata-runtime-updates-to-github.md",
      "sortKey": "2026-06-03_push-samata-runtime-updates-to-github.md",
      "date": "2026-06-03",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/deployment"
      ],
      "topic": "插件接入"
    },
    {
      "title": "Samata 项目重构：核心平台 + 独立工具插件",
      "link": "/plan/2026-05-21_samata-refactor-plugin-based",
      "sourcePath": "docs/plan/2026-05-21_samata-refactor-plugin-based.md",
      "sortKey": "2026-05-21_samata-refactor-plugin-based.md",
      "date": "2026-05-21",
      "status": "implemented",
      "canonicalDocs": [
        "/plugins/sdk-and-lifecycle",
        "/platform/architecture"
      ],
      "topic": "插件隔离与迁移"
    },
    {
      "title": "Wiki 同步子项目",
      "link": "/plan/2026-04-27_wiki-sync-subproject",
      "sourcePath": "docs/plan/2026-04-27_wiki-sync-subproject.md",
      "sortKey": "2026-04-27_wiki-sync-subproject.md",
      "date": "2026-04-27",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/wiki-and-doc-sources",
        "/plugins/catalog"
      ],
      "topic": "后台服务插件化"
    },
    {
      "title": "Tutor 错题集升级计划",
      "link": "/plan/2026-04-23_tutor-wrong-questions",
      "sourcePath": "docs/plan/2026-04-23_tutor-wrong-questions.md",
      "sortKey": "2026-04-23_tutor-wrong-questions.md",
      "date": "2026-04-23",
      "status": "implemented",
      "canonicalDocs": [
        "/plugins/catalog"
      ],
      "topic": "工具插件目录"
    },
    {
      "title": "用 chrome-devtools-mcp 替换 @playwright/mcp",
      "link": "/plan/2026-04-23_chrome-devtools-mcp-upgrade",
      "sourcePath": "docs/plan/2026-04-23_chrome-devtools-mcp-upgrade.md",
      "sortKey": "2026-04-23_chrome-devtools-mcp-upgrade.md",
      "date": "2026-04-23",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/web-and-browser",
        "/plugins/sdk-and-lifecycle"
      ],
      "topic": "Tool / Skill / MCP"
    },
    {
      "title": "Windows 宿主机 Chrome CDP + Playwright MCP 方案",
      "link": "/plan/2026-04-16_chrome-cdp-browser-mcp",
      "sourcePath": "docs/plan/2026-04-16_chrome-cdp-browser-mcp.md",
      "sortKey": "2026-04-16_chrome-cdp-browser-mcp.md",
      "date": "2026-04-16",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/web-and-browser",
        "/plugins/sdk-and-lifecycle"
      ],
      "topic": "Tool / Skill / MCP"
    },
    {
      "title": "Agent 维度报价上传与询价功能",
      "link": "/plan/2026-04-16_agent-pricing-quote",
      "sourcePath": "docs/plan/2026-04-16_agent-pricing-quote.md",
      "sortKey": "2026-04-16_agent-pricing-quote.md",
      "date": "2026-04-16",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/pricing-and-trade",
        "/plugins/catalog"
      ],
      "topic": "工具插件目录"
    },
    {
      "title": "OTC Claw（衍语）功能架构说明",
      "link": "/plan/2026-04-12_otcclaw-architecture-overview",
      "sourcePath": "docs/plan/2026-04-12_otcclaw-architecture-overview.md",
      "sortKey": "2026-04-12_otcclaw-architecture-overview.md",
      "date": "2026-04-12",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/agent-capability-model",
        "/external-data/pricing-and-trade",
        "/plugins/sdk-and-lifecycle"
      ],
      "topic": "Tool / Skill / MCP"
    },
    {
      "title": "Plugin 热加载架构设计",
      "link": "/plan/2026-04-10_plugin-hot-load-architecture",
      "sourcePath": "docs/plan/2026-04-10_plugin-hot-load-architecture.md",
      "sortKey": "2026-04-10_plugin-hot-load-architecture.md",
      "date": "2026-04-10",
      "status": "implemented",
      "canonicalDocs": [
        "/plugins/loading-and-hot-reload"
      ],
      "topic": "加载与热更新"
    },
    {
      "title": "Agent 工具权限矩阵重构",
      "link": "/plan/2026-04-07_agent-tools-matrix-refactor",
      "sourcePath": "docs/plan/2026-04-07_agent-tools-matrix-refactor.md",
      "sortKey": "2026-04-07_agent-tools-matrix-refactor.md",
      "date": "2026-04-07",
      "status": "implemented",
      "canonicalDocs": [
        "/permissions/tool-access",
        "/plugins/bind-to-agent"
      ],
      "topic": "Agent 绑定"
    },
    {
      "title": "Add Text-to-Image and Text-to-Video Generation",
      "link": "/plan/2026-04-06_media-generation",
      "sourcePath": "docs/plan/2026-04-06_media-generation.md",
      "sortKey": "2026-04-06_media-generation.md",
      "date": "2026-04-06",
      "status": "implemented",
      "canonicalDocs": [
        "/plugins/catalog",
        "/platform/common-tools"
      ],
      "topic": "工具插件目录"
    },
    {
      "title": "Samata vs OpenClaw vs Claude Code: Skill & Tool 架构对比分析",
      "link": "/plan/2026-04-02_skill-tool-architecture-comparison",
      "sourcePath": "docs/plan/2026-04-02_skill-tool-architecture-comparison.md",
      "sortKey": "2026-04-02_skill-tool-architecture-comparison.md",
      "date": "2026-04-02",
      "status": "implemented",
      "canonicalDocs": [
        "/plugins/sdk-and-lifecycle",
        "/permissions/tool-access"
      ],
      "topic": "Tool / Skill / MCP"
    },
    {
      "title": "Skill 系统重构：向 Claude Code / openclaw 定义对齐",
      "link": "/plan/2026-03-31_skill-alignment-with-claude",
      "sourcePath": "docs/plan/2026-03-31_skill-alignment-with-claude.md",
      "sortKey": "2026-03-31_skill-alignment-with-claude.md",
      "date": "2026-03-31",
      "status": "implemented",
      "canonicalDocs": [
        "/plugins/sdk-and-lifecycle"
      ],
      "topic": "Skill 机制"
    },
    {
      "title": "Plan: Markdown → Image Tool",
      "link": "/plan/2026-03-30_markdown-to-image-tool",
      "sourcePath": "docs/plan/2026-03-30_markdown-to-image-tool.md",
      "sortKey": "2026-03-30_markdown-to-image-tool.md",
      "date": "2026-03-30",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/common-tools",
        "/plugins/catalog"
      ],
      "topic": "工具插件目录"
    },
    {
      "title": "Samata 新功能扩展设计方案",
      "link": "/plan/2026-03-25_modular-tools-mcp-doctor",
      "sourcePath": "docs/plan/2026-03-25_modular-tools-mcp-doctor.md",
      "sortKey": "2026-03-25_modular-tools-mcp-doctor.md",
      "date": "2026-03-25",
      "status": "implemented",
      "canonicalDocs": [
        "/plugins/sdk-and-lifecycle"
      ],
      "topic": "Tool / Skill / MCP"
    },
    {
      "title": "企微监测 Tools 化计划",
      "link": "/plan/2026-03-19_wework-monitor-tool",
      "sourcePath": "docs/plan/2026-03-19_wework-monitor-tool.md",
      "sortKey": "2026-03-19_wework-monitor-tool.md",
      "date": "2026-03-19",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/channels-and-sessions",
        "/plugins/catalog"
      ],
      "topic": "后台服务插件化"
    }
  ],
  "external-data": [
    {
      "title": "旧 InfluxDB 监控与 north_info 迁移脚本清理",
      "link": "/plan/2026-06-03_legacy-influxdb-monitor-cleanup",
      "sourcePath": "docs/plan/2026-06-03_legacy-influxdb-monitor-cleanup.md",
      "sortKey": "2026-06-03_legacy-influxdb-monitor-cleanup.md",
      "date": "2026-06-03",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/architecture",
        "/external-data/pricing-and-trade"
      ],
      "topic": "交易数据源迁移"
    },
    {
      "title": "Wiki Compile 性能优化",
      "link": "/plan/2026-05-19_wiki-compile-performance",
      "sourcePath": "docs/plan/2026-05-19_wiki-compile-performance.md",
      "sortKey": "2026-05-19_wiki-compile-performance.md",
      "date": "2026-05-19",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/wiki-and-doc-sources"
      ],
      "topic": "Wiki 与文档源"
    },
    {
      "title": "Wiki Architecture Redesign: 从编译型百科到链接型文档库",
      "link": "/plan/2026-05-19_wiki-architecture-redesign",
      "sourcePath": "docs/plan/2026-05-19_wiki-architecture-redesign.md",
      "sortKey": "2026-05-19_wiki-architecture-redesign.md",
      "date": "2026-05-19",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/wiki-and-doc-sources"
      ],
      "topic": "Wiki 与文档源"
    },
    {
      "title": "Wiki 编译层",
      "link": "/plan/2026-05-18_wiki-compilation-layer",
      "sourcePath": "docs/plan/2026-05-18_wiki-compilation-layer.md",
      "sortKey": "2026-05-18_wiki-compilation-layer.md",
      "date": "2026-05-18",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/wiki-and-doc-sources"
      ],
      "topic": "Wiki 与文档源"
    },
    {
      "title": "Fix Google CAPTCHA Issue for Web Search",
      "link": "/plan/2026-05-13_fix-google-captcha",
      "sourcePath": "docs/plan/2026-05-13_fix-google-captcha.md",
      "sortKey": "2026-05-13_fix-google-captcha.md",
      "date": "2026-05-13",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/web-and-browser"
      ],
      "topic": "Web 与浏览器"
    },
    {
      "title": "Wind PG 索引落地（2026-05-08）",
      "link": "/plan/2026-05-08_wind-pg-indexes",
      "sourcePath": "docs/plan/2026-05-08_wind-pg-indexes.md",
      "sortKey": "2026-05-08_wind-pg-indexes.md",
      "date": "2026-05-08",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/wind-postgres"
      ],
      "topic": "Wind PostgreSQL"
    },
    {
      "title": "TiClaw 沙箱 + Wind 数据库能力（2026-05-08）",
      "link": "/plan/2026-05-08_ticlaw-sandbox-wind",
      "sourcePath": "docs/plan/2026-05-08_ticlaw-sandbox-wind.md",
      "sortKey": "2026-05-08_ticlaw-sandbox-wind.md",
      "date": "2026-05-08",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/wind-sandbox",
        "/permissions/file-and-sandbox-allowlist"
      ],
      "topic": "Wind 与沙箱"
    },
    {
      "title": "Web 调用无结论问题改进",
      "link": "/plan/2026-05-06_web-browsing-loop-fix",
      "sourcePath": "docs/plan/2026-05-06_web-browsing-loop-fix.md",
      "sortKey": "2026-05-06_web-browsing-loop-fix.md",
      "date": "2026-05-06",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/web-and-browser",
        "/platform/observability"
      ],
      "topic": "Web 与浏览器"
    },
    {
      "title": "2026-04-29 异常会话根因分析",
      "link": "/plan/2026-04-30_loop-root-cause-analysis",
      "sourcePath": "docs/plan/2026-04-30_loop-root-cause-analysis.md",
      "sortKey": "2026-04-30_loop-root-cause-analysis.md",
      "date": "2026-04-30",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/observability",
        "/external-data/web-and-browser"
      ],
      "topic": "Web 与浏览器"
    },
    {
      "title": "Agent Wiki 知识库改造计划",
      "link": "/plan/2026-04-28_agent-wiki-knowledge",
      "sourcePath": "docs/plan/2026-04-28_agent-wiki-knowledge.md",
      "sortKey": "2026-04-28_agent-wiki-knowledge.md",
      "date": "2026-04-28",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/wiki-and-doc-sources",
        "/platform/agent-capability-model"
      ],
      "topic": "Wiki 与文档源"
    },
    {
      "title": "Wiki 同步子项目",
      "link": "/plan/2026-04-27_wiki-sync-subproject",
      "sourcePath": "docs/plan/2026-04-27_wiki-sync-subproject.md",
      "sortKey": "2026-04-27_wiki-sync-subproject.md",
      "date": "2026-04-27",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/wiki-and-doc-sources",
        "/plugins/catalog"
      ],
      "topic": "Wiki 与文档源"
    },
    {
      "title": "Trade Summary 增加极速空头汇总",
      "link": "/plan/2026-04-27_trade-summary-short-side",
      "sourcePath": "docs/plan/2026-04-27_trade-summary-short-side.md",
      "sortKey": "2026-04-27_trade-summary-short-side.md",
      "date": "2026-04-27",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/pricing-and-trade"
      ],
      "topic": "报价与交易"
    },
    {
      "title": "North Info CSV 导出工具",
      "link": "/plan/2026-04-27_north-info-export-csv",
      "sourcePath": "docs/plan/2026-04-27_north-info-export-csv.md",
      "sortKey": "2026-04-27_north-info-export-csv.md",
      "date": "2026-04-27",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/pricing-and-trade"
      ],
      "topic": "报价与交易"
    },
    {
      "title": "Agent read_file 白名单",
      "link": "/plan/2026-04-27_agent-read-file-allowlist",
      "sourcePath": "docs/plan/2026-04-27_agent-read-file-allowlist.md",
      "sortKey": "2026-04-27_agent-read-file-allowlist.md",
      "date": "2026-04-27",
      "status": "implemented",
      "canonicalDocs": [
        "/permissions/file-and-sandbox-allowlist",
        "/external-data/wind-sandbox"
      ],
      "topic": "Wind 与沙箱"
    },
    {
      "title": "Chrome DevTools MCP — Linux 本机配置",
      "link": "/plan/2026-04-24_chrome-devtools-mcp-linux-setup",
      "sourcePath": "docs/plan/2026-04-24_chrome-devtools-mcp-linux-setup.md",
      "sortKey": "2026-04-24_chrome-devtools-mcp-linux-setup.md",
      "date": "2026-04-24",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/web-and-browser"
      ],
      "topic": "Web 与浏览器"
    },
    {
      "title": "用 chrome-devtools-mcp 替换 @playwright/mcp",
      "link": "/plan/2026-04-23_chrome-devtools-mcp-upgrade",
      "sourcePath": "docs/plan/2026-04-23_chrome-devtools-mcp-upgrade.md",
      "sortKey": "2026-04-23_chrome-devtools-mcp-upgrade.md",
      "date": "2026-04-23",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/web-and-browser",
        "/plugins/sdk-and-lifecycle"
      ],
      "topic": "Web 与浏览器"
    },
    {
      "title": "执行计划：文档知识从 DB 存储改为 Markdown 文件 + Grep 查询",
      "link": "/plan/2026-04-20_documents-markdown-grep",
      "sourcePath": "docs/plan/2026-04-20_documents-markdown-grep.md",
      "sortKey": "2026-04-20_documents-markdown-grep.md",
      "date": "2026-04-20",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/agent-capability-model",
        "/external-data/wiki-and-doc-sources"
      ],
      "topic": "Wiki 与文档源"
    },
    {
      "title": "评审：文档知识 DB → Markdown + Grep 方案",
      "link": "/plan/2026-04-20_documents-markdown-grep_review",
      "sourcePath": "docs/plan/2026-04-20_documents-markdown-grep_review.md",
      "sortKey": "2026-04-20_documents-markdown-grep_review.md",
      "date": "2026-04-20",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/agent-capability-model",
        "/external-data/wiki-and-doc-sources"
      ],
      "topic": "Wiki 与文档源"
    },
    {
      "title": "调整 prompt 区分两类\"报价\"语义",
      "link": "/plan/2026-04-17_quote-semantics-prompt-fix",
      "sourcePath": "docs/plan/2026-04-17_quote-semantics-prompt-fix.md",
      "sortKey": "2026-04-17_quote-semantics-prompt-fix.md",
      "date": "2026-04-17",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/pricing-and-trade"
      ],
      "topic": "报价与交易"
    },
    {
      "title": "Pricing Schedule 工具路由修复",
      "link": "/plan/2026-04-17_pricing-schedule-tool-routing",
      "sourcePath": "docs/plan/2026-04-17_pricing-schedule-tool-routing.md",
      "sortKey": "2026-04-17_pricing-schedule-tool-routing.md",
      "date": "2026-04-17",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/pricing-and-trade"
      ],
      "topic": "报价与交易"
    },
    {
      "title": "Pricing Schedule 产品 → 管理人映射导入",
      "link": "/plan/2026-04-17_pricing-schedule-manager-mapping",
      "sourcePath": "docs/plan/2026-04-17_pricing-schedule-manager-mapping.md",
      "sortKey": "2026-04-17_pricing-schedule-manager-mapping.md",
      "date": "2026-04-17",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/pricing-and-trade"
      ],
      "topic": "报价与交易"
    },
    {
      "title": "客户报价 Excel 导入优化",
      "link": "/plan/2026-04-16_pricing-schedule-import",
      "sourcePath": "docs/plan/2026-04-16_pricing-schedule-import.md",
      "sortKey": "2026-04-16_pricing-schedule-import.md",
      "date": "2026-04-16",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/pricing-and-trade"
      ],
      "topic": "报价与交易"
    },
    {
      "title": "Windows 宿主机 Chrome CDP + Playwright MCP 方案",
      "link": "/plan/2026-04-16_chrome-cdp-browser-mcp",
      "sourcePath": "docs/plan/2026-04-16_chrome-cdp-browser-mcp.md",
      "sortKey": "2026-04-16_chrome-cdp-browser-mcp.md",
      "date": "2026-04-16",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/web-and-browser",
        "/plugins/sdk-and-lifecycle"
      ],
      "topic": "Web 与浏览器"
    },
    {
      "title": "Agent 维度报价上传与询价功能",
      "link": "/plan/2026-04-16_agent-pricing-quote",
      "sourcePath": "docs/plan/2026-04-16_agent-pricing-quote.md",
      "sortKey": "2026-04-16_agent-pricing-quote.md",
      "date": "2026-04-16",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/pricing-and-trade",
        "/plugins/catalog"
      ],
      "topic": "报价与交易"
    },
    {
      "title": "OTC Claw（衍语）功能架构说明",
      "link": "/plan/2026-04-12_otcclaw-architecture-overview",
      "sourcePath": "docs/plan/2026-04-12_otcclaw-architecture-overview.md",
      "sortKey": "2026-04-12_otcclaw-architecture-overview.md",
      "date": "2026-04-12",
      "status": "implemented",
      "canonicalDocs": [
        "/platform/agent-capability-model",
        "/external-data/pricing-and-trade",
        "/plugins/sdk-and-lifecycle"
      ],
      "topic": "报价与交易"
    },
    {
      "title": "执行计划 - 按管理人查看交易日报 Prompt 优化",
      "link": "/plan/2026-03-21_trade-daily-report-by-manager",
      "sourcePath": "docs/plan/2026-03-21_trade-daily-report-by-manager.md",
      "sortKey": "2026-03-21_trade-daily-report-by-manager.md",
      "date": "2026-03-21",
      "status": "implemented",
      "canonicalDocs": [
        "/external-data/pricing-and-trade"
      ],
      "topic": "报价与交易"
    }
  ]
};

export const uncategorizedPlanItems: PlanIndexItem[] = [
  {
    "title": "Samata Server Startup Keepalive",
    "link": "/plan/2026-06-03_samata-server-startup-keepalive",
    "sourcePath": "docs/plan/2026-06-03_samata-server-startup-keepalive.md",
    "sortKey": "2026-06-03_samata-server-startup-keepalive.md",
    "date": "2026-06-03",
    "status": "unknown",
    "canonicalDocs": [],
    "topic": "未分类"
  },
  {
    "title": "Feishu Image Context Codex Fallback",
    "link": "/plan/2026-06-03_feishu-image-context-codex-fallback",
    "sourcePath": "docs/plan/2026-06-03_feishu-image-context-codex-fallback.md",
    "sortKey": "2026-06-03_feishu-image-context-codex-fallback.md",
    "date": "2026-06-03",
    "status": "unknown",
    "canonicalDocs": [],
    "topic": "未分类"
  },
  {
    "title": "Codex Vision Image Argument Order Fix",
    "link": "/plan/2026-06-03_codex-vision-image-arg-order",
    "sourcePath": "docs/plan/2026-06-03_codex-vision-image-arg-order.md",
    "sortKey": "2026-06-03_codex-vision-image-arg-order.md",
    "date": "2026-06-03",
    "status": "unknown",
    "canonicalDocs": [],
    "topic": "未分类"
  },
  {
    "title": "Codex Image Generation Stdin Fix",
    "link": "/plan/2026-06-03_codex-imagegen-stdin-fix",
    "sourcePath": "docs/plan/2026-06-03_codex-imagegen-stdin-fix.md",
    "sortKey": "2026-06-03_codex-imagegen-stdin-fix.md",
    "date": "2026-06-03",
    "status": "unknown",
    "canonicalDocs": [],
    "topic": "未分类"
  },
  {
    "title": "Codex Agent 图片生成与识别工具",
    "link": "/plan/2026-06-03_codex-agent-vision-tools",
    "sourcePath": "docs/plan/2026-06-03_codex-agent-vision-tools.md",
    "sortKey": "2026-06-03_codex-agent-vision-tools.md",
    "date": "2026-06-03",
    "status": "unknown",
    "canonicalDocs": [],
    "topic": "未分类"
  },
  {
    "title": "修复 Agent 删除的级联清理",
    "link": "/plan/2026-05-28_fix-agent-deletion",
    "sourcePath": "docs/plan/2026-05-28_fix-agent-deletion.md",
    "sortKey": "2026-05-28_fix-agent-deletion.md",
    "date": "2026-05-28",
    "status": "unknown",
    "canonicalDocs": [],
    "topic": "未分类"
  },
  {
    "title": "Sandbox Oracle -> PostgreSQL Migration",
    "link": "/plan/2026-05-07_sandbox-oracle-to-postgres",
    "sourcePath": "docs/plan/2026-05-07_sandbox-oracle-to-postgres.md",
    "sortKey": "2026-05-07_sandbox-oracle-to-postgres.md",
    "date": "2026-05-07",
    "status": "archived",
    "canonicalDocs": [],
    "topic": "未归入正式模块"
  },
  {
    "title": "近两周功能更新摘要（04/09–04/23）",
    "link": "/plan/2026-04-23_recent-changes-summary",
    "sourcePath": "docs/plan/2026-04-23_recent-changes-summary.md",
    "sortKey": "2026-04-23_recent-changes-summary.md",
    "date": "2026-04-23",
    "status": "archived",
    "canonicalDocs": [],
    "topic": "未归入正式模块"
  },
  {
    "title": "otcclaw 移除 generate_video / extract_wework_qa",
    "link": "/plan/2026-04-14_otcclaw-remove-video-wework-qa",
    "sourcePath": "docs/plan/2026-04-14_otcclaw-remove-video-wework-qa.md",
    "sortKey": "2026-04-14_otcclaw-remove-video-wework-qa.md",
    "date": "2026-04-14",
    "status": "archived",
    "canonicalDocs": [],
    "topic": "未归入正式模块"
  },
  {
    "title": "Plan: README 同步更新",
    "link": "/plan/2026-04-05_readme-sync",
    "sourcePath": "docs/plan/2026-04-05_readme-sync.md",
    "sortKey": "2026-04-05_readme-sync.md",
    "date": "2026-04-05",
    "status": "archived",
    "canonicalDocs": [],
    "topic": "未归入正式模块"
  },
  {
    "title": "Plan: Merge tutor branch into main",
    "link": "/plan/2026-03-19_merge-tutor",
    "sourcePath": "docs/plan/2026-03-19_merge-tutor.md",
    "sortKey": "2026-03-19_merge-tutor.md",
    "date": "2026-03-19",
    "status": "archived",
    "canonicalDocs": [],
    "topic": "未归入正式模块"
  }
];
